// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdkGjW-AIUSikz8Hj51XC_ewAKoNJZVog',
    appId: '1:730010590764:web:9f8cfa700c7be27b39bb89',
    messagingSenderId: '730010590764',
    projectId: 'chat-app-be630',
    authDomain: 'chat-app-be630.firebaseapp.com',
    storageBucket: 'chat-app-be630.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscOaPRE-acMsXtFVUHwO3XltyAgmYAGM',
    appId: '1:730010590764:android:719473942d30b0e539bb89',
    messagingSenderId: '730010590764',
    projectId: 'chat-app-be630',
    storageBucket: 'chat-app-be630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuB985cA8MuOtkSEu-BKtTo8GXpAL_Ke8',
    appId: '1:730010590764:ios:0821ca10d409a79239bb89',
    messagingSenderId: '730010590764',
    projectId: 'chat-app-be630',
    storageBucket: 'chat-app-be630.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuB985cA8MuOtkSEu-BKtTo8GXpAL_Ke8',
    appId: '1:730010590764:ios:0821ca10d409a79239bb89',
    messagingSenderId: '730010590764',
    projectId: 'chat-app-be630',
    storageBucket: 'chat-app-be630.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdkGjW-AIUSikz8Hj51XC_ewAKoNJZVog',
    appId: '1:730010590764:web:0bb3f538d451a34d39bb89',
    messagingSenderId: '730010590764',
    projectId: 'chat-app-be630',
    authDomain: 'chat-app-be630.firebaseapp.com',
    storageBucket: 'chat-app-be630.appspot.com',
  );
}
